### ISSUE TITLE
Navigation : changer Accueil en Musée de l'Elysée

### ISSUE THREAD

**Issue by elyseelab** [vdch/elyseech#177]
Peut-on changer Accueil en Musée de l'Elysée dans la navigation sans casser l'url existante ?

En valid j'ai fait comme ça : 
Titre de la page : Musée de l'Elysée
Titre de navigation alternatif : Accueil 
Le soucis c'est que le titre de page n'est plus accueil, mais Musée de l'Elysée : Musée de l'Elysée.

Ce que veux c'est mettre Musée de l'Elysée dans la navigation mais que le titre de la page soit toujours Musée de l'Elysée : accueil. 

D'après #173 la navigation alternative n'est pas configurée.

**Comment by jlthirot** [comment]
Est-ce que ce cas peut être fermé ?

**Comment by elyseelab** [comment]
Oui
