### ISSUE TITLE
Carte des expos : ne s'affiche plus

### ISSUE THREAD

**Issue by elyseelab** [vdch/elyseech#182]
La carte des expos (id=7132) : http://www.elysee.ch/expositions-et-evenements/expositions-dans-le-monde/carte/ ne s'affiche plus alors que sur l'ancienne page (id=4019) elle fonctionne encore. 

Possible de voir ce qui se passe ?

**Comment by jlthirot** [comment]
C'est corrigé

------------------------
note

<INCLUDE_TYPOSCRIPT: source="FILE:fileadmin/templates/Ely10/extensions/rggooglemap/exposItinerantes/setup_01.ts">
corrigé en
<INCLUDE_TYPOSCRIPT: source="FILE:fileadmin/templates/Ely10/extensions/rggooglemap/exposItinerantes/setup.ts">

**Comment by jlthirot** [comment]
on ne peut plus t’attribuer les cas ?

**Comment by elyseelab** [comment]
Cool !

PS : Je peux plus attribuer les cas à qui que ce soit

**Comment by elyseelab** [comment]
PS 2 : est-ce que l'un d'entre vous a déjà travaillé avec www.mapbox.com ?

**Comment by alienlebarge** [comment]
@elyseelab, j'ai créé deux cas our tes "PS" #183 #184

**Comment by jlthirot** [comment]
Je ferme ce cas
