### ISSUE TITLE
Actualités vue liste : lien

### ISSUE THREAD

**Issue by elyseelab** [vdch/elyseech#185]
Le lien "En savior plus" n'est pas cliquable dans la vue liste sur la page http://www.elysee.ch/le-musee/actualites/. Possible de le corriger ?

<img width="723" alt="capture d ecran 2015-10-05 a 15 25 45" src="https://cloud.githubusercontent.com/assets/9978840/10281575/b55b53ce-6b75-11e5-9370-e893b148a20d.png">

**Comment by elyseelab** [comment]
@jlthirot possible de regarder ou assigner qqn je peux tjs pas assigner :-)

**Comment by jlthirot** [comment]
Le code html n'est plus valide ?

```
                <!--IF(###FIELD.type### == 0)-->
                <a class="link_arrow href="###FIELD.detailLink###">
                <!--ENDIF-->
                <!--IF(###FIELD.type### == 1)-->
                <a class="link_arrow href="###FIELD.internalLink###">
                <!--ENDIF-->
                <!--IF(###FIELD.type### == 2)-->
                <a class="link_arrow href="###FIELD.externalLink###">
                <!--ENDIF-->

                        ###LLL:EXT:vdtmplelysee/Resources/Private/Language/locallang_fe.xml:news.read_more###
                    </a>

```

**Comment by jlthirot** [comment]
@elyseelab. @alienlebarge  
C'est corrigé, mais c'est étrange l'erreur date du 21.05.2015 ?
Est-ce possible ?

**Comment by elyseelab** [comment]
@jlthirot  heu je comprend pas vraiment ce que tu veux dire

**Comment by jlthirot** [comment]
@elyseelab 
Le lien devait être ko depuis le 21.05.2015. On peut fermer le cas ?

**Comment by elyseelab** [comment]
@jlthirot oui je ferme les cas.
