### ISSUE TITLE
Layout expo : éléments masqués à droite

### ISSUE THREAD

**Issue by elyseelab** [vdch/elyseech#187]
Sur cette page : http://www.elysee.ch/expositions-et-evenements/expositions-dans-le-monde/expositions/regeneration3-foto-mx-fondacion-amparo/

Lorsque je masque l'élément tout en bas de la colonne de droit, ça masque celui du haut aussi ... 

<img width="871" alt="capture d ecran 2015-10-08 a 12 45 35" src="https://cloud.githubusercontent.com/assets/9978840/10364356/d81ec106-6dba-11e5-9281-82f89513feef.png">

**Comment by alienlebarge** [comment]
Effectivement, le fait de caché l'élément de contenu du bas cache également celui du haut.
Ce n'est pas un problème de style vu que l'élément ne s'affiche plus dans le HTML.

J'ai fait [un petit diff entre "élément du bas non caché" et "élément du bas caché"](https://gist.github.com/alienlebarge/271e4d621544f8c83129/revisions#diff-3b17ae963ca4cd3b8e345184a1725110) qui montre ça.

L'élément du haut se trouve entre [les ligne 118 et 122](https://gist.github.com/alienlebarge/271e4d621544f8c83129/revisions#diff-3b17ae963ca4cd3b8e345184a1725110L118).  
![napkin 08 10 15 2 44 12 pm](https://cloud.githubusercontent.com/assets/611234/10366482/129aaa60-6dcb-11e5-9fa0-86923a4cd66b.png)


L'élément du bas se trouve entre [les lignes 201 et 203](https://gist.github.com/alienlebarge/271e4d621544f8c83129/revisions#diff-3b17ae963ca4cd3b8e345184a1725110L201)  
![napkin 08 10 15 2 45 04 pm](https://cloud.githubusercontent.com/assets/611234/10366493/27dc3d9e-6dcb-11e5-9a90-fbac22eb1ee7.png)

Je continue de :mag:

**Comment by alienlebarge** [comment]
Le problème est le même sur toutes les pages avec le template *Expo detail layout*.

@elyseelab est-ce que tu sais si ça a eu fonctionné correctement ou si ce problème est survenu dernièrement ?
Cela me permet de mieux cibler mes recherches

**Comment by elyseelab** [comment]
@alienlebarge Je n'avais jamais vu ça avant, mais j'avais jamais eu besoin de masquer qqch en bas :-) 

Les pages : id=7347 et id=7168  utilisent le même layout si jamais t'as besoin pour tes tests.

**Comment by elyseelab** [comment]
Je crois qu'en valid on avait le problème que rien ne s'affichait en haut.

**Comment by alienlebarge** [comment]
C'est corrigé.

J'ai testé, ça semble tout bon.

**Comment by elyseelab** [comment]
@alienlebarge testé aussi ça semble bon. Merci
